### PR TITLE
feat(issues): fetch both open and closed issues, sort closed issues i…

### LINKED ISSUE #29: Sort closed issues into the done column
# Requirements
Any issues marked as `closed` should be sorted into the `done` column by default

### PR DESCRIPTION
**Pull request by QZera**
Closes #29

### CODE REVIEW

**Comment by QZera** [comment]
@gsaslis I'm prioritizing the label over the state for assigning the issues to columns. So if an issue is `closed` and has `todo` label, it will get sorted into the `todo` column.

Let me know if we want to go the other way around.

**Comment by gsaslis** [comment]
> @gsaslis I'm prioritizing the label over the state for sorted the issues to columns. So if an issue is `closed` and has a `todo` label, it will get sorted into the `todo` column.
> 
> Let me know if we want to go the other way around.

I think we would want to go the other way round, yes. ;)

**Comment by QZera** [comment]
> > @gsaslis I'm prioritizing the label over the state for sorted the issues to columns. So if an issue is `closed` and has a `todo` label, it will get sorted into the `todo` column.
> > Let me know if we want to go the other way around.
> 
> I think we would want to go the other way round, yes. ;)

Done!

**Review by gsaslis — APPROVED** [review]
Looks Good To Me (LGTM)

**Pull request merged**
