### PR TITLE
feat(board): add column re ordering

### LINKED ISSUE #38: Allow re-ordering columns
I need to be able to re-order columns to visualize my workflow, by dragging & dropping the columns.

### PR DESCRIPTION
**Pull request by QZera**
Closes #38

### CODE REVIEW

**Comment by gsaslis** [comment]
@QZera there seems to be something wrong with the cursor on macOS / brave. Please see recording. 


https://github.com/cytechmobile/radicle-planning-boards/assets/2420882/f8845c85-9d29-4319-82c7-cb9a8f03006e

**Comment by QZera** [comment]
> @QZera there seems to be something wrong with the cursor on macOS / brave. Please see recording.
> 
>  Screen.Recording.2024-01-31.at.6.17.29.PM.mov

Seems to have been caused by me hiding the ghost image on drag.

**Comment by gsaslis** [comment]
@QZera thanks - this has addressed my earlier issue.

**Review by gsaslis — APPROVED** [review]

**Comment by QZera** [comment]
@gsaslis Need another approval here (resolved conflicts after merging #46)

**Review by gsaslis — DISMISSED** [review]

**Comment by gsaslis** [comment]
@QZera hmmm I see some commits aren't signed

**Comment by QZera** [comment]
@gsaslis Should be fixed now, sorry for all the back and forth

**Review by gsaslis — APPROVED** [review]

**Pull request merged**
